name: Verify the PR
run-name: ${{ github.actor }} is verify the PR.

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]



jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:

      - name: check out branch
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: clear project
        run: mvn clean

      - name: compile the project
        run: mvn compile

      - name: Build with Maven
        run: mvn clean install